"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.formatNum = exports.bn = exports.PLANET_ZONE_THEMES_DATA = exports.HARDCODED_PLANETS_DATA = exports.ACHIEVEMENTS_DATA = exports.ACHIEVEMENT_CLAIM_CREDITS = exports.BATTLE_DURATION_MS = exports.ZONE_ALIEN_DATA = exports.SHIPS_DATA = exports.PLANET_DROP_TABLE = exports.CANNONS_DATA = exports.ULT_LEVEL_STEP = exports.MAX_ULTS_AT_MAX_LEVEL = exports.MAX_MODULE_LEVEL = exports.MODULES_DATA = exports.MAX_LEVEL = exports.XP_THRESHOLDS = exports.RESEARCH_DATA = exports.METAL_TIER_DATA = exports.SHOP_DATA = exports.EXPEDITIONS_DATA = exports.TOTAL_PLANETS = exports.TOTAL_SECTORS = exports.SECTORS_PER_ZONE = exports.PLANETS_PER_SECTOR = exports.ZONES_DATA = exports.UPGRADES_DATA = exports.FORMULA_CONSTANTS = void 0;
var formulaConstants_1 = require("./formulaConstants");
Object.defineProperty(exports, "FORMULA_CONSTANTS", { enumerable: true, get: function () { return formulaConstants_1.FORMULA_CONSTANTS; } });
var upgrades_1 = require("./upgrades");
Object.defineProperty(exports, "UPGRADES_DATA", { enumerable: true, get: function () { return upgrades_1.UPGRADES_DATA; } });
var sectors_1 = require("./sectors");
Object.defineProperty(exports, "ZONES_DATA", { enumerable: true, get: function () { return sectors_1.ZONES_DATA; } });
Object.defineProperty(exports, "PLANETS_PER_SECTOR", { enumerable: true, get: function () { return sectors_1.PLANETS_PER_SECTOR; } });
Object.defineProperty(exports, "SECTORS_PER_ZONE", { enumerable: true, get: function () { return sectors_1.SECTORS_PER_ZONE; } });
Object.defineProperty(exports, "TOTAL_SECTORS", { enumerable: true, get: function () { return sectors_1.TOTAL_SECTORS; } });
Object.defineProperty(exports, "TOTAL_PLANETS", { enumerable: true, get: function () { return sectors_1.TOTAL_PLANETS; } });
var expeditions_1 = require("./expeditions");
Object.defineProperty(exports, "EXPEDITIONS_DATA", { enumerable: true, get: function () { return expeditions_1.EXPEDITIONS_DATA; } });
var shop_1 = require("./shop");
Object.defineProperty(exports, "SHOP_DATA", { enumerable: true, get: function () { return shop_1.SHOP_DATA; } });
Object.defineProperty(exports, "METAL_TIER_DATA", { enumerable: true, get: function () { return shop_1.METAL_TIER_DATA; } });
var research_1 = require("./research");
Object.defineProperty(exports, "RESEARCH_DATA", { enumerable: true, get: function () { return research_1.RESEARCH_DATA; } });
var player_1 = require("./player");
Object.defineProperty(exports, "XP_THRESHOLDS", { enumerable: true, get: function () { return player_1.XP_THRESHOLDS; } });
Object.defineProperty(exports, "MAX_LEVEL", { enumerable: true, get: function () { return player_1.MAX_LEVEL; } });
var modules_1 = require("./modules");
Object.defineProperty(exports, "MODULES_DATA", { enumerable: true, get: function () { return modules_1.MODULES_DATA; } });
Object.defineProperty(exports, "MAX_MODULE_LEVEL", { enumerable: true, get: function () { return modules_1.MAX_MODULE_LEVEL; } });
Object.defineProperty(exports, "MAX_ULTS_AT_MAX_LEVEL", { enumerable: true, get: function () { return modules_1.MAX_ULTS_AT_MAX_LEVEL; } });
Object.defineProperty(exports, "ULT_LEVEL_STEP", { enumerable: true, get: function () { return modules_1.ULT_LEVEL_STEP; } });
var cannons_1 = require("./cannons");
Object.defineProperty(exports, "CANNONS_DATA", { enumerable: true, get: function () { return cannons_1.CANNONS_DATA; } });
var metals_1 = require("./metals");
Object.defineProperty(exports, "PLANET_DROP_TABLE", { enumerable: true, get: function () { return metals_1.PLANET_DROP_TABLE; } });
var ships_1 = require("./ships");
Object.defineProperty(exports, "SHIPS_DATA", { enumerable: true, get: function () { return ships_1.SHIPS_DATA; } });
var aliens_1 = require("./aliens");
Object.defineProperty(exports, "ZONE_ALIEN_DATA", { enumerable: true, get: function () { return aliens_1.ZONE_ALIEN_DATA; } });
Object.defineProperty(exports, "BATTLE_DURATION_MS", { enumerable: true, get: function () { return aliens_1.BATTLE_DURATION_MS; } });
var achievements_1 = require("./achievements");
Object.defineProperty(exports, "ACHIEVEMENT_CLAIM_CREDITS", { enumerable: true, get: function () { return achievements_1.ACHIEVEMENT_CLAIM_CREDITS; } });
Object.defineProperty(exports, "ACHIEVEMENTS_DATA", { enumerable: true, get: function () { return achievements_1.ACHIEVEMENTS_DATA; } });
var planets_1 = require("./planets");
Object.defineProperty(exports, "HARDCODED_PLANETS_DATA", { enumerable: true, get: function () { return planets_1.HARDCODED_PLANETS_DATA; } });
Object.defineProperty(exports, "PLANET_ZONE_THEMES_DATA", { enumerable: true, get: function () { return planets_1.PLANET_ZONE_THEMES_DATA; } });
var formatNum_1 = require("./formatNum");
Object.defineProperty(exports, "bn", { enumerable: true, get: function () { return formatNum_1.bn; } });
Object.defineProperty(exports, "formatNum", { enumerable: true, get: function () { return formatNum_1.formatNum; } });
